name: ouro
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - expat=2.7.3=h885b0b7_4
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.3=pyhc872135_0
  - python=3.11.13=h981015d_0
  - setuptools=80.9.0=py311haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py311haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - accelerate==1.12.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.12.0
      - attrs==25.4.0
      - bitsandbytes==0.49.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - contourpy==1.3.3
      - cycler==0.12.1
      - datasets==4.4.1
      - dill==0.4.0
      - filelock==3.20.0
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.18
      - networkx==3.6.1
      - numpy==2.3.5
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.0.0
      - platformdirs==4.5.1
      - propcache==0.4.1
      - protobuf==6.33.2
      - psutil==7.1.3
      - pyarrow==22.0.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - safetensors==0.7.0
      - seaborn==0.13.2
      - sentry-sdk==2.47.0
      - six==1.17.0
      - smmap==5.0.2
      - sympy==1.13.1
      - tokenizers==0.22.1
      - torch==2.6.0
      - tqdm==4.67.1
      - transformers==4.56.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.6.2
      - uv==0.9.17
      - wandb==0.23.1
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: D:\miniconda3\envs\ouro
